
import static java.lang.Math.pow;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lcferreira
 */
public class novoBaka extends javax.swing.JFrame {

    /**
     * Creates new form novoBaka
     */
    public novoBaka() {
        initComponents();
        inVisibru.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sA = new javax.swing.JSpinner();
        sB = new javax.swing.JSpinner();
        sC = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bB = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        aA = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cC = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnBaka = new javax.swing.JButton();
        inVisibru = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bakaRes = new javax.swing.JLabel();
        tipoRes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        sA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sAStateChanged(evt);
            }
        });

        sB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sBStateChanged(evt);
            }
        });

        sC.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sCStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("X^2+");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("X +");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("=");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("0");

        bB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bB.setForeground(new java.awt.Color(255, 0, 0));
        bB.setText("B");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("^2  -4*");

        aA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        aA.setForeground(new java.awt.Color(255, 0, 0));
        aA.setText("A");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("*");

        cC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cC.setForeground(new java.awt.Color(255, 0, 0));
        cC.setText("C");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Δ =");

        btnBaka.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBaka.setText("Calcular Δ");
        btnBaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBakaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Δ =");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Tipo =");

        bakaRes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bakaRes.setText("jLabel10");

        tipoRes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tipoRes.setText("jLabel");

        javax.swing.GroupLayout inVisibruLayout = new javax.swing.GroupLayout(inVisibru);
        inVisibru.setLayout(inVisibruLayout);
        inVisibruLayout.setHorizontalGroup(
            inVisibruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inVisibruLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(inVisibruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(26, 26, 26)
                .addGroup(inVisibruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bakaRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tipoRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(276, Short.MAX_VALUE))
        );
        inVisibruLayout.setVerticalGroup(
            inVisibruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inVisibruLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(inVisibruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(bakaRes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(inVisibruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tipoRes))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(sA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(16, 16, 16)
                        .addComponent(sC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(inVisibru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBaka)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(bB)
                                .addGap(3, 3, 3)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aA)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cC)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sA, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sC, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bB)
                    .addComponent(jLabel6)
                    .addComponent(aA)
                    .addComponent(jLabel8)
                    .addComponent(cC)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addComponent(btnBaka)
                .addGap(28, 28, 28)
                .addComponent(inVisibru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBakaActionPerformed
        // TODO add your handling code here:
        inVisibru.setVisible(true);
        int n1=Integer.parseInt(sA.getValue().toString());
        int n2=Integer.parseInt(sB.getValue().toString());
        int n3=Integer.parseInt(sC.getValue().toString());
        int bk=(int) (pow(n2,2)-(4*n1*n3));
        bakaRes.setText(Integer.toString(bk));
        if(bk<0)
            tipoRes.setText("Não há Raízes reais");
        else
            tipoRes.setText("Há Raízes reais");
        
    }//GEN-LAST:event_btnBakaActionPerformed

    private void sAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sAStateChanged
        // TODO add your handling code here:
        aA.setText(sA.getValue().toString());
    }//GEN-LAST:event_sAStateChanged

    private void sBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sBStateChanged
        // TODO add your handling code here:
        bB.setText(sB.getValue().toString());
    }//GEN-LAST:event_sBStateChanged

    private void sCStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sCStateChanged
        // TODO add your handling code here:
        cC.setText(sC.getValue().toString());
    }//GEN-LAST:event_sCStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(novoBaka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(novoBaka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(novoBaka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(novoBaka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new novoBaka().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aA;
    private javax.swing.JLabel bB;
    private javax.swing.JLabel bakaRes;
    private javax.swing.JButton btnBaka;
    private javax.swing.JLabel cC;
    private javax.swing.JPanel inVisibru;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner sA;
    private javax.swing.JSpinner sB;
    private javax.swing.JSpinner sC;
    private javax.swing.JLabel tipoRes;
    // End of variables declaration//GEN-END:variables
}
